### ISSUE TITLE
configmap slice points to multiple copies of the same configmap

### ISSUE THREAD

**Issue by nakato** [kelseyhightower/konfd#3]
The pointer used at https://github.com/kelseyhightower/konfd/blob/master/template.go#L120,L121 ends up pointing to something in the iterator, which changes every time we iterate, so the configmap that is the last in the iteration gets processed the number of configmaps in the namespace and no other configmap template will be processed.

**Comment by kelseyhightower** [comment]
Looks like it was a shadowing bug. Fixed in https://github.com/kelseyhightower/konfd/commit/9cb93d87409e7c7375e802a6887e6a2b4e1d4d5d
